name: update profile
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} 
          base: repositories
          plugin_languages: yes
          plugin_stargazers: yes
