name: update profile
on:
  schedule:
    - cron: '0 0 * * *' # Tự động chạy hàng ngày
  workflow_dispatch: # Cho phép kích hoạt thủ công
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Personal access token
          base: repositories
          plugin_languages: yes
          plugin_stargazers: yes
